name: All Tests
on:
  push:
    # only on commits, not on tags
    branches:
      - '**'
  pull_request:
jobs:
  tests:
    name: Lint and Playwright Tests
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: npm
      - name: Install Dependencies
        run: npm ci
      # https://playwright.dev/docs/ci#github-actions (note that page recommends not caching)
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run all tests
        run: npm run all-test
